package ec.edu.espe.dpexsystem.view;

import static java.lang.System.exit;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Sagnay
 */
public class FrmDPEXSystemMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmDPEXSystemMenu
     */
    public FrmDPEXSystemMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuDpex = new javax.swing.JMenu();
        itmLogout = new javax.swing.JMenuItem();
        itmExit = new javax.swing.JMenuItem();
        mnuElectoralPackage = new javax.swing.JMenu();
        itmRegisterPackage = new javax.swing.JMenuItem();
        itmViewPackage = new javax.swing.JMenuItem();
        mnuCountry = new javax.swing.JMenu();
        itmRegisterCountry = new javax.swing.JMenuItem();
        itmViewCountries = new javax.swing.JMenuItem();
        itmShipping = new javax.swing.JMenu();
        itmShippingPackage = new javax.swing.JMenuItem();
        itmRecount = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("¡Bienvenido!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("en el exterior");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 550, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("N40-, Av. Gaspar de Villarroel ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setText("& Av. Río Amazonas, Quito");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setText("República del Ecuador");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 640, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/dpexsystem/others/240_F_77092802_l5epJqExIj3BEkeN9bEreTDepkpIPaR0.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 470, 230));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sistema del Departamento de Procesos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 550, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(183, 251, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 51));
        jMenuBar1.setOpaque(true);

        mnuDpex.setText("DPEX System");

        itmLogout.setText("Cerrar Sesión");
        itmLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmLogoutActionPerformed(evt);
            }
        });
        mnuDpex.add(itmLogout);

        itmExit.setText("Salir");
        itmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExitActionPerformed(evt);
            }
        });
        mnuDpex.add(itmExit);

        jMenuBar1.add(mnuDpex);

        mnuElectoralPackage.setText("Paquetes Electorales");
        mnuElectoralPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuElectoralPackageActionPerformed(evt);
            }
        });

        itmRegisterPackage.setText("Registrar");
        itmRegisterPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegisterPackageActionPerformed(evt);
            }
        });
        mnuElectoralPackage.add(itmRegisterPackage);

        itmViewPackage.setText("Ver Paquetes");
        mnuElectoralPackage.add(itmViewPackage);

        jMenuBar1.add(mnuElectoralPackage);

        mnuCountry.setText("País");

        itmRegisterCountry.setText("Registrar");
        itmRegisterCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegisterCountryActionPerformed(evt);
            }
        });
        mnuCountry.add(itmRegisterCountry);

        itmViewCountries.setText("Ver Paises");
        itmViewCountries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmViewCountriesActionPerformed(evt);
            }
        });
        mnuCountry.add(itmViewCountries);

        jMenuBar1.add(mnuCountry);

        itmShipping.setText("Administrador");

        itmShippingPackage.setText("Envio de Paquetes");
        itmShippingPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmShippingPackageActionPerformed(evt);
            }
        });
        itmShipping.add(itmShippingPackage);

        itmRecount.setText("Reconteo de Paquetes");
        itmRecount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRecountActionPerformed(evt);
            }
        });
        itmShipping.add(itmRecount);

        jMenuBar1.add(itmShipping);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmRegisterPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegisterPackageActionPerformed
        FrmElectoralPackage frmElectoralPackage = new FrmElectoralPackage();
        this.setVisible(false);
        frmElectoralPackage.setVisible(true);
    }//GEN-LAST:event_itmRegisterPackageActionPerformed

    private void itmRegisterCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegisterCountryActionPerformed
        FrmCountry frmCountry = new FrmCountry();
        this.setVisible(false);
        frmCountry.setVisible(true);
    }//GEN-LAST:event_itmRegisterCountryActionPerformed

    private void itmLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLogoutActionPerformed
        int selection;
        selection = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro?");
        if(selection == JOptionPane.YES_OPTION){
            FrmLogin frmLogin = new FrmLogin();
            this.setVisible(false);
            frmLogin.setVisible(true);
        }

    }//GEN-LAST:event_itmLogoutActionPerformed

    private void mnuElectoralPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuElectoralPackageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuElectoralPackageActionPerformed

    private void itmViewCountriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmViewCountriesActionPerformed
        FrmViewCountry frmViewCountries = new FrmViewCountry();
        this.setVisible(false);
        frmViewCountries.setVisible(true);
    }//GEN-LAST:event_itmViewCountriesActionPerformed

    private void itmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExitActionPerformed
        exit(0);
    }//GEN-LAST:event_itmExitActionPerformed

    private void itmShippingPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmShippingPackageActionPerformed
        FrmShipping frmShipping = new FrmShipping();
        this.setVisible(false);
        frmShipping.setVisible(true);
    }//GEN-LAST:event_itmShippingPackageActionPerformed

    private void itmRecountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRecountActionPerformed
        FrmRecount frmRecount = new FrmRecount();
        this.setVisible(false);
        frmRecount.setVisible(true);
    }//GEN-LAST:event_itmRecountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDPEXSystemMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDPEXSystemMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDPEXSystemMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDPEXSystemMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDPEXSystemMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmExit;
    private javax.swing.JMenuItem itmLogout;
    private javax.swing.JMenuItem itmRecount;
    private javax.swing.JMenuItem itmRegisterCountry;
    private javax.swing.JMenuItem itmRegisterPackage;
    private javax.swing.JMenu itmShipping;
    private javax.swing.JMenuItem itmShippingPackage;
    private javax.swing.JMenuItem itmViewCountries;
    private javax.swing.JMenuItem itmViewPackage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu mnuCountry;
    private javax.swing.JMenu mnuDpex;
    private javax.swing.JMenu mnuElectoralPackage;
    // End of variables declaration//GEN-END:variables
}
